=== tomerazran/EDPNAMFilters/misc/oauth_authorization_filter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://edp.co.il/oauth_authorization_filter/" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:edp="http://edp.co.il/oauth_authorization_filter/">
    <element name="config" type="edp:oAuthFilterConfig"></element>
    
    <complexType name="oAuthFilterConfig">
    	<sequence>
    		<element name="publicScopes" type="edp:scopes" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="clientSpecificScopes" type="edp:clientSpecificScopes"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="clientSpecificScopes">
    	<sequence>

    		<element name="clientScopes" type="edp:clientScopes"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="scopes">
    	<sequence>
    		<element name="scope" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="clientScopes">
    	<sequence>
    		<element name="clientID" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="scopes" type="edp:scopes" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== tomerazran/EDPNAMFilters/misc/oauth_authorization_filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<edp:config xmlns:edp="http://edp.co.il/oauth_authorization_filter/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://edp.co.il/oauth_authorization_filter/ oauth_authorization_filter.xsd ">
  <publicScopes>
    <scope>address</scope>
    <scope>profile</scope>
  </publicScopes>
  <clientSpecificScopes>
    <clientScopes>
      <clientID>428269de-79d7-42a3-905a-d08668538228</clientID>
      <scopes>
        <scope>email</scope>
      </scopes>
    </clientScopes>
    <clientScopes>
      <clientID>412349de-79d7-42a3-905a-d08668531118</clientID>
      <scopes>
        <scope>email</scope>
        <scope>phone</scope>
      </scopes>
    </clientScopes>
  </clientSpecificScopes>
</edp:config>
